### ISSUE TITLE
[M3] Prototyping

### ISSUE THREAD

**Issue by yucan-yu** [donovan361/ICT2101-2201-Team-Project#73]
Create UI using Figma

**Comment by yucan-yu** [comment]
Inclusive of all staff, manager and IT admin pages

**Comment by yucan-yu** [comment]
Manager pages: Donovan and Yi Xuan
Staff pages: Ye Kai
IT admin pages + linking: Yucan

**Comment by yekai11** [comment]
Finalised figma prototype
